version: '3'

services:
  backend:
    build: 
      context : ./backend
    ports:
      - '5000:5000'
    

  frontend:
    build: 
      context: ./frontend/vue-app
    ports:
      - '8080:8080'
    depends_on:
      - backend
